name: flutter_fitness_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  google_fonts: ^6.3.1
  cloud_firestore: ^6.0.2
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5+1
  pedometer: ^4.1.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/foods.json
