// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARwZmAlL3un-n6cW4NhKYf1HJ-djNnBlw',
    appId: '1:433214188950:web:89c4c319fd45dbe1a241b7',
    messagingSenderId: '433214188950',
    projectId: 'flutter-auth-app-248dd',
    authDomain: 'flutter-auth-app-248dd.firebaseapp.com',
    storageBucket: 'flutter-auth-app-248dd.firebasestorage.app',
    measurementId: 'G-DGHGGNMV56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqRLjUM0fFU-XZlX1Cy2lqcBv6eTTWAcI',
    appId: '1:433214188950:android:57f3e26faf6d6fb1a241b7',
    messagingSenderId: '433214188950',
    projectId: 'flutter-auth-app-248dd',
    storageBucket: 'flutter-auth-app-248dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxS4y9h_S4TfXDfRBk1Kwo3ZPFSc9Z_vM',
    appId: '1:433214188950:ios:526c88e27dce5abda241b7',
    messagingSenderId: '433214188950',
    projectId: 'flutter-auth-app-248dd',
    storageBucket: 'flutter-auth-app-248dd.firebasestorage.app',
    iosBundleId: 'com.example.flutterFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxS4y9h_S4TfXDfRBk1Kwo3ZPFSc9Z_vM',
    appId: '1:433214188950:ios:526c88e27dce5abda241b7',
    messagingSenderId: '433214188950',
    projectId: 'flutter-auth-app-248dd',
    storageBucket: 'flutter-auth-app-248dd.firebasestorage.app',
    iosBundleId: 'com.example.flutterFitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARwZmAlL3un-n6cW4NhKYf1HJ-djNnBlw',
    appId: '1:433214188950:web:2f099ce34e444c83a241b7',
    messagingSenderId: '433214188950',
    projectId: 'flutter-auth-app-248dd',
    authDomain: 'flutter-auth-app-248dd.firebaseapp.com',
    storageBucket: 'flutter-auth-app-248dd.firebasestorage.app',
    measurementId: 'G-27F9WXS31G',
  );
}
